[package]
name = "spotify-discord"
version = "0.1.0"
authors = ["Russell McQueeney <rmcq@utexas.edu>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11"
tokio-core = "0.1.8"
serde = "1.0.9"
serde_json = "1.0.2"
serde_derive = "1.0.9"
hyper-tls = "0.1.2"
